/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instantmessenger;

import static instantmessenger.InstantMessenger.database;
import java.io.PrintStream;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Saketh
 */
public class FTablePrint extends javax.swing.JFrame {

    /**
     * Creates new form FTablePrint
     */
    PrintStream outOrg = System.out;
    public FTablePrint() {
        initComponents();
        this.getRootPane().setDefaultButton(btnConnect);
    }
    FLogin login;
    FChat chat;
    public void getFrames(FLogin L, FChat C){
        this.login = L;
        this.chat = C;
    }
    
    
    public void displayFrnds(){
        try {
            database.getFriendsList();
            ResultSetMetaData met = database.resultSet.getMetaData();
            int numberOfColumns = met.getColumnCount();
            
            
            PrintStream printStream = new PrintStream(new CustomOutputStream(txtArea));
            //PrintStream printStream = new PrintStream(System.out);
            System.setOut(printStream);
            System.setErr(printStream);
            try {
                database.getFriendsList();
                database.resultSet.beforeFirst();
                
                while(database.resultSet.next()){
                    for(int i=1;i<=numberOfColumns;i++)
                        System.out.printf("%-8s\t", database.resultSet.getObject(i));
                    System.out.println();
                }
                
                System.setOut(this.outOrg);
                //txtFrnd.requestFocus();
            }
            catch (SQLException ex) {
                //Logger.getLogger(FTablePrint.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        catch (SQLException ex)
        {  //         Logger.getLogger(FTablePrint.class.getName()).log(Level.SEVERE, null, ex);
            //Logger.getLogger(FTablePrint.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFrnd = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnConnect = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(334, 460));
        setResizable(false);

        jLabel1.setText("Type in the friend's name");

        btnConnect.setText("Connect");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        txtArea.setEditable(false);
        txtArea.setBackground(new java.awt.Color(245, 245, 245));
        txtArea.setColumns(20);
        txtArea.setFont(new java.awt.Font("Levenim MT", 0, 13)); // NOI18N
        txtArea.setRows(5);
        txtArea.setFocusable(false);
        jScrollPane2.setViewportView(txtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtFrnd, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnConnect))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFrnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnConnect)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
        if((!txtFrnd.getText().equals(""))){
            try {
                String frnIP = database.getFrndIp(txtFrnd.getText());

                switch(chat.getFriend(frnIP, txtFrnd.getText())){
                    case "yes":
                        chat.setVisible(true);
                        this.setVisible(false);
                        break;
                    case "no":
                        JOptionPane.showMessageDialog(this, "Not Available!");
                        break;
                    default:
                        txtFrnd.setText("");
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, "User doesn't exist");
            }
        }
    }//GEN-LAST:event_btnConnectActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FTablePrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FTablePrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FTablePrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FTablePrint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FTablePrint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConnect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextField txtFrnd;
    // End of variables declaration//GEN-END:variables
}
